In [11]:
import pandas as pd

In [12]:
df = pd.read_excel("datasets/online_retail_II.xlsx")
df.to_csv("datasets/online_retail_II.csv", index = False)

In [13]:
df = pd.read_csv("datasets\online_retail_II.csv")

In [14]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [18]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [16]:
df.shape

(525461, 8)

In [17]:
df.size

4203688

In [19]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=525461, step=1)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  object
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 32.1+ MB

In [24]:
df.describe()

            Quantity          Price    Customer ID
count  525461.000000  525461.000000  417534.000000
mean       10.337667       4.688834   15360.645478
std       107.424110     146.126914    1680.811316
min     -9600.000000  -53594.360000   12346.000000
25%         1.000000       1.250000   13983.000000
50%         3.000000       2.100000   15311.000000
75%        10.000000       4.210000   16799.000000
max     19152.000000   25111.090000   18287.000000

In [34]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [29]:
df["StockCode"].unique()
# df["Invoice"].unique()

array(['85048', '79323P', '79323W', ..., '22935', '22933', '21120'],
      dtype=object)

In [33]:
df['InvoiceDate'] = pd.to_datetime(df["InvoiceDate"])

In [43]:
df.info()
df["InvoiceDate"].dt.time

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

0         07:45:00
1         07:45:00
2         07:45:00
3         07:45:00
4         07:45:00
            ...
525456    20:01:00
525457    20:01:00
525458    20:01:00
525459    20:01:00
525460    20:01:00
Name: InvoiceDate, Length: 525461, dtype: object

In [44]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [ ]:
print(df["Invoice"].value_counts())
print(df["StockCode"].value_counts())


print(df["Country"].value_counts())
# print(df["Invoice"].value_counts())

Invoice
537434     675
538071     652
537638     601
537237     597
536876     593
          ...
C489504      1
C489476      1
489467       1
489463       1
C538164      1
Name: count, Length: 28816, dtype: int64
StockCode
85123A    3516
22423     2221
85099B    2057
21212     1933
21232     1843
          ...
72045A       1
21863        1
21862        1
21052        1
79151B       1
Name: count, Length: 4632, dtype: int64
Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
                                      ...
HEN PARTY BANNER TAPE                    1
?sold individually?                      1
NEW BAROQUE BLACK BOXES                  1
SILICON CUBE 25W, BLUE                   1
6 HOOK JEWEL STAND LILAC DRESS           1
Name: count, Length: 4681, dtype: int64
Quantity
1       146118
2        78131
12       60682
6        44431
3        35517
         ...
131          1
286          1
1540         1
127          1
133          1
Name: count, Length: 825, dtype: int64
InvoiceDate
2010-12-06 16:57:00    675
2010-12-09 14:09:00    652
2010-12-07 15:28:00    601
2010-12-06 09:58:00    597
2010-12-03 11:36:00    593
                      ...
2010-01-07 16:21:00      1
2010-10-18 15:55:00      1
2010-10-18 15:52:00      1
2010-12-09 16:11:00      1
2010-12-09 15:54:00      1
Name: count, Length: 25296, dtype: int64
Price
1.25       53932
0.85       40721
2.95       38094
1.65       35627
2.10       24701
           ...
10.19          1
701.95         1
52.77          1
5519.25        1
183.32         1
Name: count, Length: 1606, dtype: int64
Customer ID
14911.0    5710
17841.0    5114
14606.0    3927
14156.0    2710
12748.0    2665
           ...
17557.0       1
14190.0       1
13551.0       1
17546.0       1
13231.0       1
Name: count, Length: 4383, dtype: int64
Country
United Kingdom          485852
EIRE                      9670
Germany                   8129
France                    5772
Netherlands               2769
Spain                     1278
Switzerland               1187
Portugal                  1101
Belgium                   1054
Channel Islands            906
Sweden                     902
Italy                      731
Australia                  654
Cyprus                     554
Austria                    537
Greece                     517
United Arab Emirates       432
Denmark                    428
Norway                     369
Finland                    354
Unspecified                310
USA                        244
Japan                      224
Poland                     194
Malta                      172
Lithuania                  154
Singapore                  117
RSA                        111
Bahrain                    107
Canada                      77
Thailand                    76
Hong Kong                   76
Israel                      74
Iceland                     71
Korea                       63
Brazil                      62
West Indies                 54
Bermuda                     34
Nigeria                     32
Lebanon                     13
Name: count, dtype: int64

In [47]:
print(df["Description"].value_counts())
print(df["Quantity"].value_counts())
print(df["InvoiceDate"].value_counts())

Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
                                      ...
HEN PARTY BANNER TAPE                    1
?sold individually?                      1
NEW BAROQUE BLACK BOXES                  1
SILICON CUBE 25W, BLUE                   1
6 HOOK JEWEL STAND LILAC DRESS           1
Name: count, Length: 4681, dtype: int64
Quantity
1       146118
2        78131
12       60682
6        44431
3        35517
         ...
131          1
286          1
1540         1
127          1
133          1
Name: count, Length: 825, dtype: int64
InvoiceDate
2010-12-06 16:57:00    675
2010-12-09 14:09:00    652
2010-12-07 15:28:00    601
2010-12-06 09:58:00    597
2010-12-03 11:36:00    593
                      ...
2010-01-07 16:21:00      1
2010-10-18 15:55:00      1
2010-10-18 15:52:00      1
2010-12-09 16:11:00      1
2010-12-09 15:54:00      1
Name: count, Length: 25296, dtype: int64

In [48]:
print(df["Price"].value_counts())
print(df["Customer ID"].value_counts())

Price
1.25       53932
0.85       40721
2.95       38094
1.65       35627
2.10       24701
           ...
10.19          1
701.95         1
52.77          1
5519.25        1
183.32         1
Name: count, Length: 1606, dtype: int64
Customer ID
14911.0    5710
17841.0    5114
14606.0    3927
14156.0    2710
12748.0    2665
           ...
17557.0       1
14190.0       1
13551.0       1
17546.0       1
13231.0       1
Name: count, Length: 4383, dtype: int64

In [58]:
df["Invoice"].str.startswith("C").sum()

np.int64(10206)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [61]:
df["Customer ID"].isnull().sum()
df["Description"].isnull().sum()

np.int64(2928)

In [64]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [67]:
df["Description"].value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
                                      ...
HEN PARTY BANNER TAPE                    1
?sold individually?                      1
NEW BAROQUE BLACK BOXES                  1
SILICON CUBE 25W, BLUE                   1
6 HOOK JEWEL STAND LILAC DRESS           1
Name: count, Length: 4681, dtype: int64

In [63]:
df["InvoiceDate"].max()

Timestamp('2010-12-09 20:01:00')

In [122]:
df.groupby("Country")["Customer ID"].nunique().sort_values(ascending=False)

Country
United Kingdom          3971
Germany                   67
France                    47
Spain                     25
Netherlands               22
Portugal                  18
Belgium                   17
Sweden                    16
Australia                 15
Switzerland               14
Italy                     11
Channel Islands           11
Austria                   10
Denmark                    9
Finland                    7
Cyprus                     7
Japan                      6
USA                        6
Norway                     5
EIRE                       5
Unspecified                4
United Arab Emirates       4
Greece                     4
Bahrain                    2
Israel                     2
Korea                      2
Poland                     2
Brazil                     1
Singapore                  1
Canada                     1
Iceland                    1
Malta                      1
Thailand                   1
RSA                        1
Lithuania                  1
Nigeria                    1
West Indies                1
Bermuda                    0
Lebanon                    0
Hong Kong                  0
Name: Customer ID, dtype: int64

In [102]:
(df[df["Country"] == "Bermuda"]["Customer ID"])
(df["Country"] == "Bermuda").value_counts()

Country
False    525427
True         34
Name: count, dtype: int64

In [103]:
print((df[df["Country"] == "Lebanon"]["Customer ID"]))
(df["Country"] == "Lebanon").value_counts()

336798   NaN
336799   NaN
336800   NaN
336801   NaN
336802   NaN
336803   NaN
336804   NaN
336805   NaN
336806   NaN
336807   NaN
336808   NaN
336809   NaN
401707   NaN
Name: Customer ID, dtype: float64

Country
False    525448
True         13
Name: count, dtype: int64

In [104]:
print((df[df["Country"] == "Lebanon"]["Customer ID"]))
(df["Country"] == "Hong Kong").value_counts()

336798   NaN
336799   NaN
336800   NaN
336801   NaN
336802   NaN
336803   NaN
336804   NaN
336805   NaN
336806   NaN
336807   NaN
336808   NaN
336809   NaN
401707   NaN
Name: Customer ID, dtype: float64

Country
False    525385
True         76
Name: count, dtype: int64

In [108]:
df["Customer ID"].isnull().sum()

np.int64(107927)

In [115]:
df[df["Customer ID"].isna()].Country.value_counts()

Country
United Kingdom          106429
EIRE                       960
United Arab Emirates       114
Portugal                    77
Hong Kong                   76
Bahrain                     65
France                      62
RSA                         46
Bermuda                     34
Unspecified                 30
Sweden                      19
Lebanon                     13
Nigeria                      2
Name: count, dtype: int64

In [116]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [117]:
df = df[~df["Invoice"].str.startswith("C")]

In [118]:
df["Invoice"].str.startswith("C").sum()

np.int64(0)

In [123]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [127]:
df.shape

(515255, 8)

In [134]:
df["Invoice"].nunique()
# df["Customer ID"].nunique()

24224

In [137]:
df[df["Customer ID"].isna()].nunique()

Invoice        5009
StockCode      4405
Description    3943
Quantity        599
InvoiceDate    3813
Price          1057
Customer ID       0
Country          12
dtype: int64

In [138]:
df["Total"] = df['Price'] * df["Quantity"]

C:\Users\anmol\AppData\Local\Temp\ipykernel_12032\1146084534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total"] = df['Price'] * df["Quantity"]

In [141]:
total_revenue = df["Total"].sum()
print(total_revenue)

10169340.004000003

In [145]:
Nan_revenue = df[df["Customer ID"].isna()]["Total"].sum()
print(Nan_revenue)

1337336.73

In [148]:
(Nan_revenue/total_revenue) * 100

np.float64(13.150673784866793)

In [155]:
df["Total"].sort_values(ascending=False).unique()

array([ 25111.09,  15818.4 ,  13541.33, ..., -38925.87, -44031.79,
       -53594.36])

In [156]:
(df["Price"] < 0).sum()

np.int64(3)

In [157]:
(df["Quantity"] < 0).sum()

np.int64(2121)

In [175]:
(df["Total"] <= 0).sum()

np.int64(3690)

In [161]:
df[df["Price"] < 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom,-53594.36
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom,-44031.79
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom,-38925.87

In [162]:
df[df["Quantity"] < 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom,-0.0
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom,-0.0
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom,-0.0
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom,-0.0
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom,-0.0
...,...,...,...,...,...,...,...,...,...
524458,538092,37467,NaN,-177,2010-12-09 14:49:00,0.0,NaN,United Kingdom,-0.0
525231,538159,21324,NaN,-18,2010-12-09 17:17:00,0.0,NaN,United Kingdom,-0.0
525232,538158,20892,NaN,-32,2010-12-09 17:17:00,0.0,NaN,United Kingdom,-0.0
525234,538161,46000S,Dotcom sales,-100,2010-12-09 17:25:00,0.0,NaN,United Kingdom,-0.0
525235,538162,46000M,Dotcom sales,-100,2010-12-09 17:25:00,0.0,NaN,United Kingdom,-0.0

In [176]:
df[df["Total"] <= 0]["Customer ID"].isna().sum()

np.int64(3659)

In [ ]:
df = df[df["Customer ID"].notnull()]



1.Converted InvoiceDate to datetime.

2.Created Total = Quantity × Price.

3.Identified and removed cancelled invoices (Invoice starts with C).

4.Investigated negative values and found accounting entries (Adjust bad debt).

5.Investigated descriptions and identified operational/system records.
Separated records with missing Customer ID for customer-level analysis instead of deleting them permanently.

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 407695 entries, 0 to 525460
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      407695 non-null  object
 1   StockCode    407695 non-null  object
 2   Description  407695 non-null  object
 3   Quantity     407695 non-null  int64
 4   InvoiceDate  407695 non-null  datetime64[ns]
 5   Price        407695 non-null  float64
 6   Customer ID  407695 non-null  float64
 7   Country      407695 non-null  object
 8   Total        407695 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 31.1+ MB

In [180]:
df.to_csv("datasets/online_retail_rfm_working_data.csv", index=False)